remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: CL-ISAAC
description: Optimized Common Lisp version of Bob Jenkins' ISAAC-32 and ISAAC-64 algorithms, fast cryptographic random number generators.
logo: /assets/images/cl-isaac-logo.png
